### ISSUE TITLE
pls tell me,how can let it work 

### ISSUE THREAD

**Issue by yoyosuka** [hangim/kcp-shadowsocks-docker#1]
http://app.arukas.io ,it's free docker.
i want this work, how to do in this website?
pls,thanks

---

update: it works! thank u,good programm!

---

but udp don't work,pls tell me how to set?

**Comment by pdszhh** [comment]
in apps.arukas.io, you can't use UDP Forwarding, because they don't allow exposed udp and tcp in a same port.

for example, when you try exposed 443(tcp) and 443(udp), you will get
443 -> 30001(tcp)
443 -> 30002(udp)
