### ISSUE TITLE
想问下，为什么默认关闭压缩，并且不能在ENV中配置

### ISSUE THREAD

**Issue by masiqi** [hangim/kcp-shadowsocks-docker#7]
如题，谢谢

**Comment by pdszhh** [comment]
Most of modern web server(Nginx, Apache, Etc.) use Gzip as default to compressing data.
So why to achieve a very little improve at the cost of higher latency time and cpu time waste?
By the way, this question has been discussed a lot of times in shadowsocks implement.

Ref:
https://github.com/shadowsocks/shadowsocks/issues/76
